name: eagle_hubb
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_launcher_icons: "^0.13.1"
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.1.7 # Add this line to include the url_launcher package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/unt.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/unt.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/unt.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/unt.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Bruceteria.png
    - images/Champs.png
    - images/EagleLanding.png
    - images/KitchenWest.png
    - images/MeanGreensCafe.png
    - i_theme/
