class FoodItems {
  final String foodName;
  final String cafeteria;
  final bool hasEggs;
  final bool hasMilk;
  final bool hasPork;
  final bool hasShellfish;
  final bool hasFish;
  final bool hasPeanuts;
  final bool hasSesame;
  final bool hasSoy;
  final bool hasTreeNuts;
  final bool hasWheat;
  final String ingredients;

  const FoodItems({
    required this.foodName,
    required this.cafeteria,
    required this.hasEggs,
    required this.hasMilk,
    required this.hasPork,
    required this.hasShellfish,
    required this.hasFish,
    required this.hasPeanuts,
    required this.hasSesame,
    required this.hasSoy,
    required this.hasTreeNuts,
    required this.hasWheat,
    required this.ingredients,
  });
}

const allFoodItems = [
  FoodItems(
    foodName: "100% Plant-based Tofu Hash",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "100% Plant-based Scrambled Tofu (Hard Tofu, Soy Milk , Extra Virgin Olive Oil , Granulated Garlic , Yeast , Top Flake Kosher Salt, Turmeric), Green Bell Pepper, Yellow Onions, Roma Tomato, Yukon Potato Gold",
  ),
  FoodItems(
    foodName: "Assorted Breakfast Pastries",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: true,
    hasWheat: true,
    ingredients:
        "Coffee Cake (Coffee Cake 4 oz (Creme Cake (Creme Cake Mix, Water (Water), Whole Egg (Whole egg, citric acid, salt.), Vegetable Oil ), All Purpose Flour, Brown Sugar, Butter Unsalted, Walnut Pieces , Cinnamon )), Assorted Muffins (Oat Bran Muffin (Creme Cake Mix, Whole Egg (Whole egg, citric acid, salt.), Water (Water), Molasses, Apples Fuji, Vegetable Oil , Rolled Oats, Dark Raisins, Rolled Oats, Bran Flakes Cereal, Baking Powder, Ground Cinnamon, Ground Nutmeg), Chocolate Chocolate Chip Muffin (Chocolate Creme Cake Mix, Water (Water), Whole Egg (Whole egg, citric acid, salt.), White Chocolate Chips, Semi-Sweet Chocolate, Vegetable Oil ), Sour Cream Blueberry Muffin (Chocolate Creme Cake Mix, Water (Water), Whole Egg (Whole egg, citric acid, salt.), Vegetable Oil , Blueberries, Sour Cream), Cappuccino Muffin (Creme Cake Mix, Water (Water), Whole Egg (Whole egg, citric acid, salt.), Vegetable Oil , Semi Sweet Chocolate Chips, Coffee Extract , Ground Cinnamon), Apple Streusel Muffin (Creme Cake Mix, Apples Fuji, Whole Eggs Frozen, All Purpose Flour, Bran Flakes Cereal, Brown Sugar, Vegetable Oil , Butter Unsalted, Sugar , Caramel Food Coloring, Cinnamon , Baking Powder), Carrot Raisin Spice Muffin (Semolina Flour, Water (Water), Sugar , Vegetable Oil , Whole Egg (Whole egg, citric acid, salt.), Shredded Carrots , Dark Raisins, Shredded Coconut, Baking Powder, Nonfat Powdered Milk, Ground Cinnamon, Top Flake Kosher Salt), Banana Nut Muffin (Creme Cake Mix, Banana Puree, Walnut Pieces , Semolina Flour, Vegetable Oil , Water (Water), Powdered Egg , Baking Soda), Chocolate Chip Muffin (Creme Cake Mix, Water (Water), Semi Sweet Chocolate Chips, Vegetable Oil , Pure Vanilla Extract)), Danish (Danish Dough (Water (Water), Semolina Flour, Butter Unsalted, Sugar , Powdered Egg , Butter Unsalted, Nonfat Powdered Milk, Yeast , Pure Vanilla Extract, Top Flake Kosher Salt, Ground Cardamon, Ground Nutmeg), Cherry Pie Filling), Croissants (Croissant Dough (Booked) (Unbooked Croissant Dough (All Purpose Flour, Water (Water), Butter Unsalted, Sugar , Nonfat Powdered Milk, Top Flake Kosher Salt, Yeast ), Whole Eggs Frozen))",
  ),
  FoodItems(
    foodName: "Baked Ham",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Cured Ham 2/10 LB",
  ),
  FoodItems(
    foodName: "Bruceteria's Biscuit Bake",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Clark Bakery Biscuits (All Purpose Flour, Water (Water), Butter Unsalted, Sugar , Powdered Buttermilk, Powdered Egg , Top Flake Kosher Salt, Cream of Tartar), Whole Egg (Whole egg, citric acid, salt.), Shredded Monterrey Jack Cheese, Whole Milk, Sausage Links, Top Flake Kosher Salt, Black Pepper",
  ),
  FoodItems(
    foodName: "Cheesy Grits",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Quick Grits, Water (Water), Whole Milk, Cheddar Shred Cheese , Whole Egg (Whole egg, citric acid, salt.), Butter , Dry Parmesan Cheese, Granulated Garlic , Garlic",
  ),
  FoodItems(
    foodName: "Chorizo Breakfast Tacos",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Diana's Roasted Salsa (Roma Tomato, Yellow Onions, Cilantro, Garlic), Whole Egg (Whole egg, citric acid, salt.), Flour Tortilla, Sausage Chorizo Bulk, Shredded Monterrey Jack Cheese",
  ),
  FoodItems(
    foodName: "Clark Bakery Biscuits",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "All Purpose Flour, Water (Water), Butter Unsalted, Sugar , Powdered Buttermilk, Powdered Egg , Top Flake Kosher Salt, Cream of Tartar",
  ),
  FoodItems(
    foodName: "Fluffy Pancakes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients: "Water (Water), Waffle Mix",
  ),
  FoodItems(
    foodName: "Fried Potatoes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Red Potatoes, Yellow Onions, Red Bell Pepper, Green Bell Pepper, Montreal Steak Seasoning",
  ),
  FoodItems(
    foodName: "Hard Boiled Eggs",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Fresh Eggs",
  ),
  FoodItems(
    foodName: "Maple Syrup",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Pancake Syrup",
  ),
  FoodItems(
    foodName: "Scrambled Eggs",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Whole Egg (Whole egg, citric acid, salt.), Butter",
  ),
  FoodItems(
    foodName: "Sizzling Sausage Links",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Sausage Links",
  ),
  FoodItems(
    foodName: "Crustless Quiche with Bacon",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Whole Egg (Whole egg, citric acid, salt.), Baby Spinach, Whole Milk, Pizza Blend Shredded Cheese, Sliced Mushrooms (Mushrooms), Roma Tomato, Bacon, Italian Parsley , Top Flake Kosher Salt, Black Pepper",
  ),
  FoodItems(
    foodName: "French Toast",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Mean Greens Sourdough (HG Flour, Water (Water), Sourdough Starter (Water (Water), HG Flour), Water (Water), Top Flake Kosher Salt, Diastatic Malt, Yeast , Vegetable Oil ), Whole Milk, Whole Egg (Whole egg, citric acid, salt.), Butter , Sugar , Imitation Vanilla Extract, Ground Cinnamon",
  ),
  FoodItems(
    foodName: "Ham Scramble",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Whole Egg (Whole egg, citric acid, salt.), Cheddar Shred Cheese , Cured Ham 2/10 LB, Baby Spinach, Butter",
  ),
  FoodItems(
    foodName: "Roasted Jalapeno Sausage",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Smoked Sausage Rope, Yukon Potato Gold, Yellow Onions, Green Bell Peppers, Red Bell Pepper, Water (Water), Garlic, Chicken Base",
  ),
  FoodItems(
    foodName: "Crispy Bacon",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Bacon",
  ),
  FoodItems(
    foodName: "Brown Sugar Oatmeal",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Brown Sugar Oatmeal",
  ),

  //start of lunch
  FoodItems(
    foodName: "Garlic Rice",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Water (Water), Parboiled Long Grain Rice , Garlic, Butter , Italian Parsley , Vegetable Base, Top Flake Kosher Salt, Pepper Black Ground",
  ),
  FoodItems(
    foodName: "Homestyle Green Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Fresh Whole Green Beans, 2 LB, Yellow Onions, Top Flake Kosher Salt",
  ),
  FoodItems(
    foodName: "Korean Beef and Rice",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Round Beef Inside (IBP ), Green Bell Peppers, Red Onions, Red Bell Pepper, Soy Sauce, Brown Sugar, Green Onions, Garlic, Rice Wine Vinegar, Toasted Sesame Seed Oil, Hulled Sesame Seed, Ground Ginger Spice, Crushed Red Pepper",
  ),
  FoodItems(
    foodName: "Kung Pao Garbanzo Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Garbanzo Beans, Red Onions, Red Bell Pepper, Green Onions, Soy Sauce, Rice Wine Vinegar, Honey Syrup, Granulated Garlic , Granulated Garlic , Toasted Sesame Seed Oil, Crushed Red Pepper , Ground Ginger Spice, Ground Ginger Spice",
  ),
  FoodItems(
    foodName: "Sauteed Cabbage",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Green Cabbage , Yellow Onions, Jumbo Carrots , Soy Sauce",
  ),
  FoodItems(
    foodName: "Soft Rolls",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "HG Flour, Water (Water), Dough Conditioner , Water (Water), Sugar , Butter Unsalted, Wheat Flour , Nonfat Powdered Milk, Yeast",
  ),
  FoodItems(
    foodName: "Sweet And Sour Rotisserie Chicken Marinade",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Rice Wine Vinegar, Ketchup Pack, Brown Sugar, Water (Water), Corn Starch",
  ),
  FoodItems(
    foodName: "Sweet Chile Broccoli",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Fresh Broccoli Floret, Sweet Chili Sauce, Soy Sauce, Canola Salad Oil, Pepper Black Ground",
  ),
  FoodItems(
    foodName: "Teriyaki Pork Loin",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Pork Loin, Concentrated Orange Juice, Brown Sugar, Corn Starch , Vegetable Oil , Garlic, Pure Sesame Oil, Ginger Root, Soy Sauce",
  ),
  FoodItems(
    foodName: "Assorted Bars",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: true,
    hasWheat: true,
    ingredients:
        "Blondies (Blondie Bar (Brown Sugar, All Purpose Flour, Butter Unsalted, Fresh Eggs , Walnut Pieces , Pure Vanilla Extract, Baking Powder, Top Flake Kosher Salt)), Magic Bars (Hello Dolly Bar (Sweetened Condensed Milk, Chocolate Supreme Cake Mix, Semi Sweet Chocolate Chips, Shredded Coconut, Walnut Pieces , Butter Unsalted, 2% Reduced Fat Milk, Pure Vanilla Extract)), Eagle Landing Mint Bar (Graham Cracker Crumbs, Vanilla Buttercream Icing, Butter Unsalted, Walnut Pieces , Shredded Coconut, Powdered Sugar , Vegetable Oil , Green Food Coloring, Pure Peppermint Extract), Brownies (Brownie Mix Extra Moist, Water (Water), Semi Sweet Chocolate Chips), Rice Krispy Treat (Rice Krispy Treat (Mini Marshmallows, Rice Krispies Cereal , Butter Unsalted))",
  ),
  FoodItems(
    foodName: "Assorted Cakes",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "German Chocolate Cake (German Chocolate Cake (Sugar , All Purpose Flour, Buttermilk, All Purpose Shortening , GERMAN CHOCOLATE FROSTING (Brown Sugar, Margarine ), Semi-Sweet Chocolate, Water (Water), Powdered Egg , Egg Yolks Sugared, Pure Vanilla Extract, Top Flake Kosher Salt, Baking Soda)), Pineapple Upside Down Cake (Crushed Pineapple, Yellow Cake Mix, Maraschino Cherries, Brown Sugar, Pure Honey, Butter Unsalted, Vegetable Oil , Imitation Rum Extract, Ground Cinnamon), Cheesecake (NY Style Cheesecake, Whole (Cream Cheese, Graham Cracker Crumbs, Whole Egg (Whole egg, citric acid, salt.), Sugar , Whipping Cream, Butter Unsalted, Sugar , Corn Starch , Pure Vanilla Extract)), Chocolate Cake (Chocolate Cake (Water (Water), Chocolate Supreme Cake Mix, Vegetable Oil ), Chocolate Buttercream Icing (Chocolate Buttercream), Comm - Simple Syrup (Water (Water), Sugar )), Hummingbird Cake (White Cake (Water (Water), White Cake Mix , Vegetable Oil ), Cream Cheese Icing, Banana Puree, Crushed Pineapple, Ground Cinnamon, Allspice)",
  ),
  FoodItems(
    foodName: "Assorted Cobblers",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Peach Filling , Cherry Pie Filling, Peaches, Red Tart Cherries, Fuji Apple Slices, All Purpose Flour, Butter , Sugar",
  ),
  FoodItems(
    foodName: "Assorted Cookies",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: true,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "M&M Cookies (M&M COOKIES (All Purpose Flour, Brown Sugar, Sugar , Butter Unsalted, Water (Water), M & M Plain , Powdered Egg , Light Corn Syrup , Clear Gel Starch, Top Flake Kosher Salt, Baking Soda, Baking Powder, Pure Vanilla Extract)), Dark Choc White Choc Chip Cookies (Chocolate White Chocolate Chip Cookie (All Purpose Flour, Butter Unsalted, White Chocolate Chips, Semi-Sweet Chocolate, Brown Sugar, Whole Egg (Whole egg, citric acid, salt.), Vanilla Pudding, Sugar , Cocoa Powder, Baking Soda)), Peanut Butter Cookie (Peanut Butter Cookies 2oz (Peanut Butter Creamy, Butter Unsalted, Sugar , Brown Sugar, Powdered Egg , Top Flake Kosher Salt, Baking Powder, Pure Vanilla Extract)), Chocolate Chip Cookies (All Purpose Flour, Semi Sweet Chocolate Chips, Butter Unsalted, Brown Sugar, Sugar , Water (Water), Powdered Egg , Light Corn Syrup , Baking Soda, Baking Powder, Top Flake Kosher Salt, Pure Vanilla Extract), Oatmeal Raisin Cookie (Oatmeal Raisin Cookie (Brown Sugar, Rolled Oats, Butter Unsalted, Water (Water), Dark Raisins, Powdered Egg , Ground Cinnamon, Pure Vanilla Extract))",
  ),
  FoodItems(
    foodName: "Chocolate Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Ice Cream Mix (Milk, Cream, Sugar, Nonfat Milk, Corn Syrup, Whey, Mono- and Diglycerides, Locust Bean Gum, Guar Gum, Carrageenan), Sugar , Cocoa Powder, Pure Vanilla Extract",
  ),
  FoodItems(
    foodName: "Mint Chocolate Chip Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Ice Cream Mix (Milk, Cream, Sugar, Nonfat Milk, Corn Syrup, Whey, Mono- and Diglycerides, Locust Bean Gum, Guar Gum, Carrageenan), Mini Chocolate Chips",
  ),
  FoodItems(
    foodName: "Strawberry Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Strawberry Ice Cream (Ice Cream Mix (Milk, Cream, Sugar, Nonfat Milk, Corn Syrup, Whey, Mono- and Diglycerides, Locust Bean Gum, Guar Gum, Carrageenan), Strawberries , Pure Vanilla Extract)",
  ),
  FoodItems(
    foodName: "Vanilla Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Ice Cream Mix (Milk, Cream, Sugar, Nonfat Milk, Corn Syrup, Whey, Mono- and Diglycerides, Locust Bean Gum, Guar Gum, Carrageenan), Pure Vanilla Extract, Vanilla Paste",
  ),
  FoodItems(
    foodName: "Bruce Mac",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Bruce Pasta (Cavatappi Cellentani Pasta, Water (Water)), Bruceteria Mac & Cheese (Whole Milk, Cheese Smooth Melt 6/5 LB, Pizza Blend Shredded Cheese, Yellow Onions, Peeled Garlic, Worcestershire Sauce, Classic Hot Sauce, Extra Virgin Olive Oil , Top Flake Kosher Salt, Paprika)",
  ),
  FoodItems(
    foodName: "Bruce Pasta",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients: "Cavatappi Cellentani Pasta, Water (Water)",
  ),
  FoodItems(
    foodName: "Cheese Pizza on Clark Bakery Crust",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients: "Cavatappi Cellentani Pasta, Water (Water)",
  ),
  FoodItems(
    foodName: "Creamy Alfredo Sauce",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Whipping Cream, Dry Parmesan Cheese, Whole Milk, Butter , Yellow Onions, Garlic, Extra Virgin Olive Oil , Salt",
  ),
  FoodItems(
    foodName: "Chicken Parm Pasta",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Marinara Sauce (Chopped Tomatoes, Diced Red Pimentos, Yellow Onions, Water (Water), Garlic, Balsamic Vinegar, Salt, Italian Seasoning, Basil Leaves, Fresh Lemon Juice , Rubbed Sage), Bruce Pasta (Cavatappi Cellentani Pasta, Water (Water)), Pizza Blend Shredded Cheese, Chicken Tenders, Part Skim Ricotta Cheese, Dry Parmesan Cheese, Baby Spinach",
  ),
  FoodItems(
    foodName: "Ham & Cheddar Pasta",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Bruceteria Mac & Cheese (Whole Milk, Cheese Smooth Melt 6/5 LB, Pizza Blend Shredded Cheese, Yellow Onions, Peeled Garlic, Worcestershire Sauce, Classic Hot Sauce, Extra Virgin Olive Oil , Top Flake Kosher Salt, Paprika), Bruce Pasta (Cavatappi Cellentani Pasta, Water (Water)), Pizza Blend Shredded Cheese, Fresh Broccoli Floret, Cured Ham 2/10 LB, Dry Parmesan Cheese",
  ),
  FoodItems(
    foodName: "Marinara Sauce",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Chopped Tomatoes, Diced Red Pimentos, Yellow Onions, Water (Water), Garlic, Balsamic Vinegar, Salt, Italian Seasoning, Basil Leaves, Fresh Lemon Juice , Rubbed Sage",
  ),
  FoodItems(
    foodName: "Pepperoni Pizza on Clark Bakery Crust",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Pizza Dough (Caputo Pizza Flour, Water (Water), Poolish (Water (Water), HG Flour, Yeast ), Sourdough Starter (Water (Water), HG Flour), Extra Virgin Olive Oil , Top Flake Kosher Salt, Yeast ), Marinara Sauce (Chopped Tomatoes, Diced Red Pimentos, Yellow Onions, Water (Water), Garlic, Balsamic Vinegar, Salt, Italian Seasoning, Basil Leaves, Fresh Lemon Juice , Rubbed Sage), Pizza Blend Shredded Cheese, Sliced Pepperoni",
  ),
  FoodItems(
    foodName: "Veggie Pizza on Clark Bakery Crust",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Pizza Dough (Caputo Pizza Flour, Water (Water), Poolish (Water (Water), HG Flour, Yeast ), Sourdough Starter (Water (Water), HG Flour), Extra Virgin Olive Oil , Top Flake Kosher Salt, Yeast ), Pizza Blend Shredded Cheese, Sliced Black Olives, Green Bell Pepper, Red Bell Pepper, Sliced Mushrooms (Mushrooms)",
  ),
  FoodItems(
    foodName: "Barbacoa Tacos",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Round Beef Inside (IBP ), Barbacoa Paste (Peppers Chile Guajillo, Yellow Onions, Water (Water), Garlic, Black Pepper , Bay Leaves, Whole Cloves), Top Flake Kosher Salt, Bay Leaves",
  ),
  FoodItems(
    foodName: "Chicken Tinga",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Chicken Breast, Diced Tomatoes, Chopped Tomatoes, Water (Water), Yellow Onions, Chipotle Pepper, Fresh Oregano, Ground Cumin, Chicken Base",
  ),
  FoodItems(
    foodName: "Coconut Curry Tofu",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Hard Tofu, Organic Coconut Milk, Yellow Onions, Cilantro, Vegetable Oil , Garlic, Lime Juice, Sugar",
  ),
  FoodItems(
    foodName: "Cowboy Charro Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Dried Pinto Beans, Water (Water), Tomato Paste, Fresh Jalapenos, White Onion, Bacon, Chicken Base, Peeled Garlic, Ground Cumin, Ancho Chili Powder, Cilantro, Fresh Oregano, Pepper Black Ground, Top Flake Kosher Salt",
  ),
  FoodItems(
    foodName: "Spanish Rice",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Water (Water), Parboiled Long Grain Rice , Tomato Paste, Vegetable Oil , Garlic, Top Flake Kosher Salt",
  ),
  FoodItems(
    foodName: "Street Corn",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Whole Kernel Corn, Sour Cream, Dry Parmesan Cheese, Cilantro, Fresh Lime Juice, Top Flake Kosher Salt, Chili Powder Light",
  ),
  FoodItems(
    foodName: "Herbed Carrots & Celery",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Jumbo Carrots , Parsley Flakes, Top Flake Kosher Salt, Granulated Garlic , Dill Weed, Cilantro",
  ),
  FoodItems(
    foodName: "Pinto Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Dried Pinto Beans, Bay Leaves, Red Bell Pepper, Yellow Onions, Bacon, Granulated Garlic , Chili Powder Light, Paprika, Ground Cumin, Ground Cayenne Pepper",
  ),
  FoodItems(
    foodName: "Rosemary Tilapia",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: true,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Tilapia, Lemons, Fresh Lemon Juice , Fresh Lemon Juice , Sugar , Fresh Rosemary, Top Flake Kosher Salt, Dijon Mustard, Trad Maille",
  ),
  FoodItems(
    foodName: "Shrimp Jambalaya",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: true,
    hasFish: true,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Water (Water), Shrimp Raw P&D, Chicken Breast HALAL, Parboiled Long Grain Rice , Cured Ham 2/10 LB, Rotel Tomatoes & Chiles, Green Bell Pepper, Yellow Onions, Italian Parsley , Chicken Base, Garlic, Tabasco Sauce, Top Flake Kosher Salt, Ground Thyme, Black Pepper",
  ),
  FoodItems(
    foodName: "Chimichurri Rotisserie",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Chicken Whole, Granulated Garlic , Crushed Red Pepper , Sweet Smoked Paprika, Black Pepper , Basil Leaves, Thyme Leaves, Parsley Flakes, Fresh Oregano, Top Flake Kosher Salt",
  ),
  FoodItems(
    foodName: "Curried Potatoes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Red Potatoes, Water (Water), Yellow Onions, Chopped Garlic, Canola Salad Oil, Italian Parsley , Salt, Fresh Lemon Juice , Turmeric, Coriander, Ground Cayenne Pepper, Ground Cinnamon",
  ),
  FoodItems(
    foodName: "Garlic Fried Rice",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Water (Water), Parboiled Long Grain Rice , Garlic, Canola Salad Oil, Toasted Sesame Seed Oil, Fresh Eggs , Soy Sauce",
  ),
  FoodItems(
    foodName: "Gochu Tofu Stir Fry",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Hard Tofu, Gochujang Paste, Toasted Sesame Seed Oil, Chopped Garlic, Corn Starch",
  ),
  FoodItems(
    foodName: "Kung Pao Chicken and Rice",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: true,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: true,
    hasWheat: true,
    ingredients:
        "Hard Tofu, Gochujang Paste, Toasted Sesame Seed Oil, Chopped Garlic, Corn Starch",
  ),
  FoodItems(
    foodName: "BBQ Baked Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Dried Navy Beans, Ketchup Pack, Brown Sugar, Yellow Onions, Bacon, French's Mustard, Worcestershire Sauce, Molasses, Top Flake Kosher Salt",
  ),
  FoodItems(
    foodName: "BBQ Chicken",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Chicken Breast, Schmidty BBQ Sauce (Ketchup Pack, Molasses, Apple Cider Vinegar, Brown Sugar, Paprika, Smoke Sauce, Onion Powder , Granulated Garlic , Ancho Chili Powder, Worcestershire Sauce, Ground Mustard, Ground Cloves), Bruce's BBQ Rub (Onion Powder , Ancho Chili Powder, Coarse Black Pepper, Paprika, Brown Sugar, Ground Mustard, Salt, Ground Cumin, Ground Cayenne Pepper)",
  ),
  FoodItems(
    foodName: "Chickpea Curry Aloo",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: true,
    hasWheat: false,
    ingredients:
        "Water (Water), Garbanzo Beans, Yellow Onions, Potatoes, Chopped Tomatoes, Shredded Coconut, Plain Greek Yogurt (Cultured Milk), Fresh Mint, Coriander, Extra Virgin Olive Oil , Cinnamon Sticks, Whole Cloves, Salted Roasted Cashews, Garlic, Chili Green Peppers, Ground Mace, Anise Seed Spice, Basil Leaves, Top Flake Kosher Salt, Fennel Seeds, Garam Masala Spice, Chili Powder Light, Cumin , Turmeric",
  ),
  FoodItems(
    foodName: "Korean BBQ Rotisserie Chicken",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: true,
    hasWheat: false,
    ingredients:
        "Chicken Whole, Soy Sauce, Brown Sugar, Rice Vinegar, Water (Water), Garlic, Sriracha Hot Chili Sauce, Chinese Five Spice, Corn Starch , Pepper Black Ground",
  ),
  FoodItems(
    foodName: "Smoked Pork Loin",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Pork Loin, Paprika, Top Flake Kosher Salt, Brown Sugar, Thyme Leaves, Fresh Oregano, Granulated Garlic , Mesquite BBQ Seasoning, Ground Cumin, Black Pepper , Chili Powder Light, Ground Cayenne Pepper",
  ),
  FoodItems(
    foodName: "Peruvian Tofu & Vegetables",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Hard Tofu, Frozen English Peas, White FS Mushroom, Wine Vinegar, Soy Sauce, Kalamata Olives, Pitted, Jumbo Carrots , Yellow Onions, Capote Capers, Tomato Paste, Garlic, Basil Leaves, Toasted Sesame Seed Oil, Top Flake Kosher Salt, Vegetable Oil , Ground Cinnamon, Ground Cayenne Pepper",
  ),

  //dinner includes all bakery, ice creame, and pizza/pastas, only entrees change
  FoodItems(
    foodName: "Broccoli & Mushrooms",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Fresh Broccoli Floret, Sliced Mushrooms (Mushrooms)",
  ),
  FoodItems(
      foodName: "Cajun Black Eyed Peas",
      cafeteria: "Bruceteria",
      hasEggs: false,
      hasMilk: true,
      hasPork: true,
      hasShellfish: false,
      hasFish: false,
      hasPeanuts: false,
      hasSesame: false,
      hasSoy: true,
      hasTreeNuts: false,
      hasWheat: true,
      ingredients:
          "Dry Black-Eyed Peas, Water (Water), Bacon, Chicken Base, Cajun Blackened Seasoning, Tabasco Sauce, Bay Leaves"),
  FoodItems(
    foodName: "Cajun Style Mustard Greens",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Mustard Greens, Water (Water), Vegetable Oil , Top Flake Kosher Salt, Ground Cayenne Pepper",
  ),
  FoodItems(
    foodName: "Ratatouille",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Eggplant, Zucchini Squash, Diced Tomatoes, Yellow Onions, Green Bell Pepper, Water (Water), Canola Salad Oil, Vegetable Base, Garlic, Black Pepper , Basil Leaves, Fresh Oregano",
  ),
  FoodItems(
    foodName: "Shrimp Etouffee",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: true,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Water (Water), Shrimp Raw P&D, Classic Hot Sauce, Chicken Base, Green Onions, Garlic, Fresh Celery, Red Bell Pepper, Yellow Onions, Butter , Fresh Jalapenos, Paprika, Celery Seeds",
  ),
  FoodItems(
    foodName: "Creamy Mashed Potatoes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Potatoes, Whipping Cream, Butter , Granulated Garlic , Top Flake Kosher Salt, Black Pepper",
  ),
  FoodItems(
    foodName: "Roasted Vegetables",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Red Onions, Zucchini Squash, Straight Neck Yellow Squash, White Small Button Mushroom, Red Bell Pepper, Green Bell Pepper, Balsamic Vinegar",
  ),
  FoodItems(
    foodName: "Stewed Black Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Water (Water), Water (Water), Black Beans, Yellow Onions, Red Bell Pepper, Canola Salad Oil, Fresh Oregano, Top Flake Kosher Salt, Garlic, Bay Leaves, Black Pepper , Ground Cumin",
  ),
  FoodItems(
    foodName: "Turkey Pot Pie",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Pie Dough (Harvest King Flour, Butter Unsalted, Water (Water), Sea Salt Kosher Coarse), Roast Turkey, Water (Water), Jumbo Carrots , Whipping Cream, Frozen English Peas, Water (Water), Yellow Onions, Thyme Leaves, Chicken Base, Rubbed Sage, Top Flake Kosher Salt, Fresh Rosemary",
  ),
  FoodItems(
    foodName: "Chicken & Dumplings",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Dumplings (Southern Biscuits (Clark Bakery Biscuits (All Purpose Flour, Water (Water), Butter Unsalted, Sugar , Powdered Buttermilk, Powdered Egg , Top Flake Kosher Salt, Cream of Tartar)), All Purpose Flour), Whipping Cream, Yellow Onions, Water (Water), Fresh Celery, Jumbo Carrots , Chicken Base, Fresh Rosemary, Fresh Thyme, Black Pepper",
  ),
  FoodItems(
    foodName: "Corn on the Cob",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Corn on the Cob, Butter",
  ),
  FoodItems(
    foodName: "Ranch Roasted Potatoes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Ranch Dressing Mix w/msg , Vegetable Oil , Black Pepper",
  ),
  FoodItems(
    foodName: "Roasted Brussels Sprouts",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Brussel Sprouts, Balsamic Vinegar, Honey Syrup, Top Flake Kosher Salt, Ground White Pepper",
  ),
  FoodItems(
    foodName: "Seasoned Rice Pilaf",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Chicken Base, Butter , Parboiled Long Grain Rice , Red Onions, Garlic, Soy Sauce, Worcestershire Sauce, Parsley Flakes",
  ),
  FoodItems(
    foodName: "Stewed Okra with Tomatoes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Fzn Whole Okra, Yellow Onions, Diced Tomatoes, Cajun Blackened Seasoning, Water (Water), Corn Starch , Top Flake Kosher Salt",
  ),
  FoodItems(
    foodName: "Sweet and Spicy Chicken",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Chicken Breast, Rice Wine Vinegar, Water (Water), Soy Sauce, Brown Sugar, Corn Starch , Garlic, Ginger Root, Classic Hot Sauce, Crushed Red Pepper",
  ),
  FoodItems(
    foodName: "Beef Tacos",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
    ingredients:
        "Ground Beef, Flour Tortilla, Diced Tomatoes, Cilantro, Yellow Onions, Granulated Garlic , Lime Juice, Top Flake Kosher Salt, Sweet Smoked Paprika, Ground Cumin, Pepper Black Ground, Chili Powder Light",
  ),
  FoodItems(
    foodName: "Refried Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Water (Water), Dried Pinto Beans, Canola Salad Oil, Tex Mex Spice Rub (Top Flake Kosher Salt, Paprika, Garlic Powder, Onion Powder , Ground Cumin, Chili Powder Light, Black Pepper ), Peeled Garlic, Top Flake Kosher Salt, White Onion",
  ),
  FoodItems(
    foodName: "BASMATI RICE",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients: "Basmati Rice, Water (Water), Cumin",
  ),
  FoodItems(
    foodName: "Bombay Potatoes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Red Potatoes, Yellow Onions, Canola Salad Oil, Turmeric, Ground Curry Powder, Top Flake Kosher Salt",
  ),
  FoodItems(
    foodName: "Chicken Tikka Masala",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
    ingredients:
        "Chicken Breast, Chopped Tomatoes, Yellow Onions, Whipping Cream, Paprika, Chipotle Pepper, Cilantro, Ground Curry Powder, Chili Powder Light, Ground Ginger Spice, Top Flake Kosher Salt, Ground Cumin, Garlic, Turmeric, GARAM MASALA (Ground Cardamon, Coriander, Ground Cumin, Ground Nutmeg, Ground Cloves, Ground Cinnamon, Black Pepper )",
  ),
];
