class FoodItems {
  final String foodName;
  final String cafeteria;
  final bool hasEggs;
  final bool hasMilk;
  final bool hasPork;
  final bool hasShellfish;
  final bool hasFish;
  final bool hasPeanuts;
  final bool hasSesame;
  final bool hasSoy;
  final bool hasTreeNuts;
  final bool hasWheat;

  const FoodItems({
    required this.foodName,
    required this.cafeteria,
    required this.hasEggs,
    required this.hasMilk,
    required this.hasPork,
    required this.hasShellfish,
    required this.hasFish,
    required this.hasPeanuts,
    required this.hasSesame,
    required this.hasSoy,
    required this.hasTreeNuts,
    required this.hasWheat,
  });
}

const allFoodItems = [
  FoodItems(
    foodName: "100% Plant-based Tofu Hash",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Assorted Breakfast Pastries",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: true,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Baked Ham",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Bruceteria's Biscuit Bake",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Cheesy Grits",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Chorizo Breakfast Tacos",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Clark Bakery Biscuits",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Fluffy Pancakes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Fried Potatoes",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Hard Boiled Eggs",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Maple Syrup",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Scrambled Eggs",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Sizzling Sausage Links",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  //start of lunch
  FoodItems(
    foodName: "Garlic Rice",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Homestyle Green Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Korean Beef and Rice",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Kung Pao Garbanzo Beans",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Sauteed Cabbage",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Soft Rolls",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Sweet And Sour Rotisserie Chicken Marinade",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Sweet Chile Broccoli",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Teriyaki Pork Loin",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: true,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Assorted Bars",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: true,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Assorted Cakes",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Assorted Cobblers",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Assorted Cookies",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: true,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Chocolate Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Mint Chocolate Chip Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Strawberry Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Vanilla Ice Cream",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Bruce Mac",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Bruce Pasta",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Cheese Pizza on Clark Bakery Crust",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Creamy Alfredo Sauce",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Chicken Parm Pasta",
    cafeteria: "Bruceteria",
    hasEggs: true,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Ham & Cheddar Pasta",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Marinara Sauce",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Pepperoni Pizza on Clark Bakery Crust",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Veggie Pizza on Clark Bakery Crust",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  //dinner includes all bakery, ice creame, and pizza/pastas, only entrees change
  FoodItems(
    foodName: "Broccoli & Mushrooms",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Cajun Black Eyed Peas",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: true,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Cajun Style Mustard Greens",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Ratatouille",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: false,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: false,
    hasTreeNuts: false,
    hasWheat: false,
  ),
  FoodItems(
    foodName: "Shrimp Etouffee",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: true,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
  FoodItems(
    foodName: "Soft Rolls",
    cafeteria: "Bruceteria",
    hasEggs: false,
    hasMilk: true,
    hasPork: false,
    hasShellfish: false,
    hasFish: false,
    hasPeanuts: false,
    hasSesame: false,
    hasSoy: true,
    hasTreeNuts: false,
    hasWheat: true,
  ),
];
